server:
    port: 8080

#openidconnect authentication
openidconnect:
    issuer-uri: https://URI:9443/oauth2endpoints/token
    issuer: https://URI.de:9443/oauth2endpoints/token
    authorizationEndpointUri: https://URI:9443/oauth2/authorize
    tokenEndpointUri: https://URI:9443/oauth2/token
    userInfoUri: https://URI:9443/oauth2/userinfo?schema=openid
    clientId: id
    clientSecret: secret
    redirectUri: http://localhost:8080/auth/openid_connect_login


spring:
    profiles:
        active: prod
    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://localhost:3306/jhipsteroidcsample
        databaseName: 
        serverName: 
        username: root
        password: 
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

    jpa:
        database-platform: org.hibernate.dialect.MySQLInnoDBDialect
        database: MYSQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
            

    mail:
        baseUrl: http://localhost:8080

    thymeleaf:
        mode: XHTML
        cache: true

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: jhipsteroidcsample

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 256M
